### ISSUE TITLE
Duplicated Results?

### ISSUE THREAD

**Issue by JasonBock** [ecoAPM/BenchmarkMockNet#14]
I was looking at the [results](https://github.com/ecoAPM/BenchmarkMockNet/blob/main/Results.md) and I noticed that both the "Construction" and "Callback" results are **exactly** the same:

![image](https://user-images.githubusercontent.com/904213/130615617-e670d829-9d9c-4aa8-a498-6ab36ee2f4f7.png)

That seems like an extreme coincidence :). Is that correct?

**Comment by stevedesmond-ca** [comment]
Posting results is still mostly manual, so it's definitely more likely that this was a copy/paste error rather than a BDN bug

**Comment by stevedesmond-ca** [comment]
Fixed as of 01211ce
