### ISSUE TITLE
Automate results extraction report as part of the run

### ISSUE THREAD

**Issue by SteveDesmond-ca** [ecoAPM/BenchmarkMockNet#15]
#14 is an example of why manually copying and pasting from BDN's results is not a good idea.

Integrate generation of the results markdown file into the actual running of the benchmarks (add ordering and description as attributes on the benchmark classes?), and upload it as an artifact in the GitHub Actions workflow.

**Comment by SteveDesmond-ca** [comment]
(not as big of a deal now that we're down to only 6 benchmarks)

**Comment by SteveDesmond-ca** [comment]
:astonished: nice work with 6.2, @JasonBock!

Automated results are now being generated, including pulling in framework version numbers.

**Comment by JasonBock** [comment]
Thanks! Does the [Results page](https://github.com/ecoAPM/BenchmarkMockNet/blob/main/Results.md) get updated automatically?

**Comment by SteveDesmond-ca** [comment]
That's still manual, as I wanted a human eyeball pass before publishing, but it's just a whole-file copy & commit now.
