### ISSUE TITLE
Add Cases for Methods With Parameters

### ISSUE THREAD

**Issue by JasonBock** [ecoAPM/BenchmarkMockNet#16]
I noticed that `IThingy` doesn't define methods with multiple parameters. I know with [Rocks](https://github.com/jasonbock/rocks) that the underlying implementation will change slightly to verify incoming argument values when parameters exist. It may be interesting to add some methods that take 1, 2, 4, etc. parameters. I'd be willing to do the PR if you think this idea has merit.

**Comment by SteveDesmond-ca** [comment]
As something to test, yes I think it's a good idea.

I've been planning on digging into the numbers to see how much the various libraries differ, and maybe drop some redundant tests (including potentially the entire "only" group) but feel free to add this and then I can rearrange after.

**Comment by SteveDesmond-ca** [comment]
Implemented as of d50d60b
